config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :permissions

      put "permissions", to: "permissions#set", as: "set_permissions"
    end

    resources :states do 
      member do 
        get :make_default 
      end
    end
  end

  root "projects#index"

  resources :projects do 
    resources :tickets
  end

  resources :tickets do 
    resources :comments
  end
  resources :files
  resources :users

  delete "/signout", to: "sessions#destroy", as: "signout"
  get '/signin', to: "sessions#new"
  post '/signin', to: "sessions#create"

end

app/models/state.rb
class State < ActiveRecord::Base

  def to_s
    name
  end

  def default!
    State.find_by(default: true).try(:update!, default: false)
    update!(default: true)
  end
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < Admin::BaseController
  def index
    @states = State.all
  end

  def new
    @state = State.new
  end

  def create
    @state = State.new(state_params)

    if @state.save
      flash[:notice] = "State has been created."
      redirect_to admin_states_path
    else
      flash[:alert] = "State has not been created."
      render "new"
    end
  end

  def make_default
    @state = State.find(params[:id])
    @state.default!

    flash[:notice] = "#{@state.name} is now the default state."
    redirect_to admin_states_path
  end

  def destroy
    @state = State.find(params[:id])
    @state.destroy
    flash[:notice] = "State has been destroyed."
    redirect_to admin_states_path
  end

  private
  
    def state_params
      params.require(:state).permit(:name, :background, :color)
    end
end

app/helpers/admin/states_helper.rb
module Admin::StatesHelper
end

app/views/admin/states/_form.html.erb
<%= form_for [:admin, @state] do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <%= f.submit %>
  <% end %>

app/views/admin/states/index.html.erb
<%= link_to "New State", new_admin_state_path %>

<ul id="states">
  <% @states.each do |state| %>
    <li id="state_<%= state.id %>">
      <%= state.name %>
      <%= link_to "Make Default",make_default_admin_state_path(state) %>
      <%= link_to "Delete State", admin_state_path(state), method: :delete, data: { confirm: "Are you sure you want to delete this state?" }  %>
    </li>
  <% end %>
</ul>

app/views/admin/states/new.html.erb
<h1>New State</h1>
<%= render 'form' %>